record error {
    code: u16,
    message: string,
}

record http-header {
    key: string,
    value: string
}

record http-request {
    method: string,
    url: string,
    params: string,
    body: string,
    headers: list<http-header>
}

record http-response {
    status: u16,
    headers: list<http-header>,
    response: string,
}

http: func(request: http-request) -> result<http-response, error>

env: func(key: string) -> result<string, error>

get: func(key: string) -> option<string>
