record error {
    code: u16,
    message: string,
  }

record http-request {
    method: string,
    url: string,
    params: string,
    body: string,
    headers: string
}

record http-response {
    status: u16,
    headers: string,
    response: string,
}

http: func(request: http-request) -> result<http-response, error>

env: func(key: string) -> result<string, error>
